name: Oppia Docker Compose Workflow

on:
  push:
    branches:
      - new  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Existing Volumes and Containers
        run: |
          docker-compose down -v
          docker-compose rm -v

      - name: Build and Run Oppia Docker Compose
        run: |
          docker-compose build
          docker compose up angular-build -d
          
      -name: Run docker Compose
       run: |
          docker-compose up -d
          
      - name: Wait for Oppia to Start
        run: |
          echo "Oppia has started. Printing logs:"
          docker-compose logs
          until $(curl --output /dev/null --silent --head --fail http://127.0.0.1:8181); do
            echo "Waiting for Oppia to start..."
            sleep 5
          done
          echo "Oppia has started. Printing logs:"
          docker-compose logs

      - name: Stop Oppia Docker Compose
        run: |
          docker-compose down
