name: Docker Workflow

on:
  push:
    branches:
      - new  # Update with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Oppia Docker Image
        run: |
          docker build -t oppia:latest .

      - name: Start Oppia Development Server
        run: |
          docker run -d -p 8181:8181 --name oppia-dev oppia:latest

      - name: Wait for Oppia to Start
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:8181); do
            echo "Waiting for Oppia to start..."
            sleep 5
          done

      - name: Run Tests or Other Tasks
        run: |
          # Add your test commands or other tasks here

      - name: Stop Oppia Development Server
        run: |
          docker stop oppia-dev
