name: Oppia Docker Compose Workflow

on:
  push:
    branches:
      - new  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Existing Volumes and Containers
        run: |
          docker-compose down -v
          docker-compose rm -v

      - name: Build and Run Oppia Docker Compose
        run: |
          docker-compose build
          docker compose up angular-build -d
          docker-compose up -d  # Start the containers in the background

      - name: Get Container ID
        id: get_container_id
        run: echo "::set-output name=container_id::$(docker ps -q --filter 'name=oppia-container')"

      - name: Execute Command Inside Container
        run: |
          container_id=${{ steps.get_container_id.outputs.container_id }}
          docker exec $container_id curl http://localhost:8181/status
          # or use your health check alternative

      - name: Stop Oppia Docker Compose
        run: |
          docker-compose down
