name: Oppia Docker Compose Workflow

on:
  push:
    branches:
      - new  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Existing Volumes and Containers
        run: |
          docker-compose down -v
          docker-compose rm -v

      - name: Build and Run Oppia Docker Compose
        run: |
          docker-compose build
          docker-compose up -d  # Start the containers in the background

      - name: Wait for Oppia to Start
        run: |
          until $(curl --output /dev/null --silent --head --fail http://localhost:8181); do
            echo "Waiting for Oppia to start..."
            sleep 5
          done

      - name: Run Tests or Other Tasks
        run: |
          # Add your test commands or other tasks here

      - name: Stop Oppia Docker Compose
        run: |
          docker-compose down
